# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306  
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  python:
    container_name: python_launcher
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile

volumes:
  mariadb_data:

  